# Generated by Django 5.0.3 on 2024-04-21 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('city_publish', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('year_published', models.DateField(default=datetime.datetime(2024, 4, 21, 13, 59, 32, 163606))),
                ('page_count', models.IntegerField()),
                ('sell_count', models.IntegerField()),
            ],
        ),
    ]
