# Generated by Django 5.0.3 on 2024-04-21 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_published',
            field=models.DateField(default=datetime.datetime(2024, 4, 21, 14, 0, 35, 894094, tzinfo=datetime.timezone.utc)),
        ),
    ]
